"""Analyze provenance signals in RAG context items."""

from __future__ import annotations

import re
from collections import Counter
from collections.abc import Iterable
from typing import Any

from graph.rag._analysis_utils import MISSING, string, value

_FIELD_GROUPS = {
    "source": ("source_url", "url", "source", "publisher"),
    "author": ("author", "byline", "creator"),
    "date": ("retrieved_at", "published_at", "updated_at", "date"),
    "citation": ("citation", "doi", "archived_url", "license", "generated_by"),
}
_TEXT_CUES = {
    "source": re.compile(r"(?i)\bsource\s*:|https?://|archived\s+at\b"),
    "author": re.compile(r"(?i)\bauthor\s*:|by\s+[A-Z][\w-]+"),
    "date": re.compile(r"(?i)\bretrieved\s+|accessed\s+|\b20\d{2}-\d{2}-\d{2}\b"),
    "citation": re.compile(r"(?i)\bcitation\s*:|\bdoi\s*:|license\s*:|generated by\b"),
}


def analyze_context_provenance_signals(context_items: Iterable[Any]) -> dict[str, Any]:
    counts: Counter[str] = Counter()
    missing: list[int] = []
    examples: list[dict[str, Any]] = []
    rows = list(context_items or [])

    for index, item in enumerate(rows):
        item_signals: list[str] = []
        for group, fields in _FIELD_GROUPS.items():
            for field in fields:
                if value(item, field) is not MISSING and string(value(item, field)) is not None:
                    key = f"metadata_{group}"
                    counts[key] += 1
                    item_signals.append(key)
                    break
        text = _text(item)
        for group, pattern in _TEXT_CUES.items():
            if pattern.search(text):
                key = f"text_{group}"
                counts[key] += 1
                item_signals.append(key)
        if not any(signal.endswith(("source", "author", "date", "citation")) for signal in item_signals):
            missing.append(index)
        elif len(examples) < 5:
            examples.append({"item_index": index, "signals": sorted(set(item_signals))})

    score = 0.0 if not rows else round((len(rows) - len(missing)) / len(rows), 2)
    return {"provenance_counts": dict(sorted(counts.items())), "missing_provenance_items": missing, "provenance_score": score, "examples": examples}


def _text(item: Any) -> str:
    if isinstance(item, str):
        return item
    return " ".join(filter(None, [string(value(item, "text")), string(value(item, "content")), string(value(item, "snippet")), string(value(item, "title"))]))
