from enum import StrEnum


class SourceProject(StrEnum):
    FORTY_TWO = "forty_two"
    MAX = "max"
    PRESENCE = "presence"
    ME = "me"
    MEDIAWIKI = "mediawiki"
    MARKDOWN_LINKS = "markdown_links"
    MASTODON = "mastodon"
    KINDLE = "kindle"
    SOTA = "sota"
    BOOKMARKS = "bookmarks"
    CSV = "csv"
    JSONL = "jsonl"
    YAML = "yaml"
    OPML = "opml"
    ORG = "org"
    PDF = "pdf"
    EMAIL = "email"
    ENEX = "enex"
    TEXT_OUTLINE = "text_outline"
    TANA_PASTE = "tana_paste"
    BIBDESK = "bibdesk"
    BIBTEX = "bibtex"
    CSL_JSON = "csl_json"
    CROSSREF = "crossref"
    RIS = "ris"
    JATS = "jats"
    GIT = "git"
    GOOGLE_KEEP = "google_keep"
    OBSIDIAN_CANVAS = "obsidian_canvas"
    NOTION_MARKDOWN = "notion_markdown"
    TRANSCRIPT = "transcript"
    POCKET = "pocket"
    POCKET_CSV = "pocket_csv"
    PINBOARD = "pinboard"
    RAINDROP = "raindrop"
    ZOTERO_RDF = "zotero_rdf"
    HYPOTHESIS = "hypothesis"
    READWISE = "readwise"
    ROAM = "roam"
    LOGSEQ = "logseq"


class ContentType(StrEnum):
    INSIGHT = "insight"
    FINDING = "finding"
    IDEA = "idea"
    DESIGN_BRIEF = "design_brief"
    ARTIFACT = "artifact"
    METADATA = "metadata"


class EdgeRelation(StrEnum):
    BUILDS_ON = "builds_on"
    CHALLENGES = "challenges"
    REFINES = "refines"
    DISCOVERS = "discovers"
    REPLICATES = "replicates"
    INSPIRES = "inspires"
    DERIVES_FROM = "derives_from"
    RELATES_TO = "relates_to"
    CONTAINS = "contains"
    REFERENCES = "references"


class EdgeSource(StrEnum):
    SOURCE = "source"
    INFERRED = "inferred"
    MANUAL = "manual"
