from enum import StrEnum


class SourceProject(StrEnum):
    FORTY_TWO = "forty_two"
    MAX = "max"
    PRESENCE = "presence"
    ME = "me"
    MEDIAWIKI = "mediawiki"
    MARKDOWN_CALLOUTS = "markdown_callouts"
    MARKDOWN_DEFINITIONS = "markdown_definitions"
    MARKDOWN_FRONTMATTER = "markdown_frontmatter"
    MARKDOWN_LINKS = "markdown_links"
    MARKDOWN_NOTES = "markdown_notes"
    MARKDOWN_TASKS = "markdown_tasks"
    MASTODON = "mastodon"
    KINDLE = "kindle"
    SOTA = "sota"
    BOOKMARKS = "bookmarks"
    BOOKMARKS_HTML = "bookmarks_html"
    BROWSER_HISTORY_CSV = "browser_history_csv"
    CHATGPT_JSON = "chatgpt_json"
    DISCORD_JSON = "discord_json"
    CSV = "csv"
    CSV_ROWS = "csv_rows"
    JSONL = "jsonl"
    JSONL_NOTES = "jsonl_notes"
    DAILY_JOURNAL = "daily_journal"
    YAML = "yaml"
    FEED = "feed"
    OPML = "opml"
    MBOX = "mbox"
    ORG = "org"
    PDF = "pdf"
    PLAIN_TEXT = "plain_text"
    EMAIL = "email"
    ENEX = "enex"
    TEXT_OUTLINE = "text_outline"
    TANA_PASTE = "tana_paste"
    BIBDESK = "bibdesk"
    BIBTEX = "bibtex"
    CSL_JSON = "csl_json"
    CROSSREF = "crossref"
    RIS = "ris"
    JATS = "jats"
    GIT = "git"
    GOOGLE_KEEP = "google_keep"
    OBSIDIAN_CANVAS = "obsidian_canvas"
    NOTION_MARKDOWN = "notion_markdown"
    TRANSCRIPT = "transcript"
    TWITTER_ARCHIVE = "twitter_archive"
    FACEBOOK_ARCHIVE = "facebook_archive"
    INSTAGRAM_ARCHIVE = "instagram_archive"
    LINKEDIN_ARCHIVE = "linkedin_archive"
    WEBVTT = "webvtt"
    POCKET = "pocket"
    POCKET_CSV = "pocket_csv"
    INSTAPAPER = "instapaper"
    PINBOARD = "pinboard"
    RAINDROP = "raindrop"
    RAINDROP_CSV = "raindrop_csv"
    RAINDROP_JSON = "raindrop_json"
    SAFARI_BOOKMARKS = "safari_bookmarks"
    ZOTERO_RDF = "zotero_rdf"
    HYPOTHESIS = "hypothesis"
    READWISE = "readwise"
    READWISE_CSV = "readwise_csv"
    GOODREADS = "goodreads"
    LETTERBOXD = "letterboxd"
    RESCUETIME = "rescuetime"
    TOGGL = "toggl"
    WAKATIME = "wakatime"
    ROAM = "roam"
    LOGSEQ = "logseq"
    SQLITE_QUERY_LOG = "sqlite_query_log"
    SLACK_JSON = "slack_json"
    VCARD = "vcard"
    YAML_FRONTMATTER = "yaml_frontmatter"


class ContentType(StrEnum):
    INSIGHT = "insight"
    FINDING = "finding"
    IDEA = "idea"
    DESIGN_BRIEF = "design_brief"
    ARTIFACT = "artifact"
    METADATA = "metadata"


class EdgeRelation(StrEnum):
    BUILDS_ON = "builds_on"
    CHALLENGES = "challenges"
    REFINES = "refines"
    DISCOVERS = "discovers"
    REPLICATES = "replicates"
    INSPIRES = "inspires"
    DERIVES_FROM = "derives_from"
    RELATES_TO = "relates_to"
    CONTAINS = "contains"
    REFERENCES = "references"
    REPLIES_TO = "replies_to"


class EdgeSource(StrEnum):
    SOURCE = "source"
    INFERRED = "inferred"
    MANUAL = "manual"
